update_config=1
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=wheel
network={
  ssid="name of network"
  #psk="network password"
  psk=egeijf8ytkjng93ghroeprgnb4g4g
  scan_ssid=1
  proto=RSN
  key_mgmt=WPA-PSK
  group=CCMP
  pairwise=CCMP
  priority=10
}
