ctrl_interface=/run/wpa_supplicant
ctrl_interface_group=wheel
update_config=1

network={
	ssid="Cumulus"
	scan_ssid=1
	psk=fcd21f63e744c61359b77f5616955f19aa456ac354e3cf2a774c2efb7bc15cd2
	mesh_fwding=1
}

network={
	ssid="Brink"
	psk="brightiris722"
	mesh_fwding=1
}

network={
	ssid="BCS GHz_2.4"
	psk="Super@1649"
	mesh_fwding=1
}

network={
	ssid="Die_Willemse"
	psk="07QJQT5FBRL"
	mesh_fwding=1
}
